name: Android CI

on:
  push:
    branches: ["main", "development" ]
  pull_request:
    branches: ["main", "development"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK 1.11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          
      - name: Set Up Gradle
        run: gradle init

      - name: Build
        run: gradle build

  Unit-Tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Initialize Gradle
        run: gradle init
      - name: List possible tests
        run: gradle test --dry-run
      - name: Run all unit tests
        run: gradle test
