name: Android CI

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]

jobs:
    -stage: build

    runs-on: ubuntu-latest

    steps:
        - name: Checkout
        uses: actions/checkout@v1

        - name: Set up JDK 1.11
            uses: actions/setup-java@v2
            with:
              java-version: '11'
              distribution: 'temurin'

        - name: Build
            run: mvn --batch-mode -DskipTests package

    -stage: unit tests
    dependsOn: build
    condition: succeded('build')
    
    steps:
        - name: Test
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test
    